version: '3.9'

services:
  api:
    image: smthngslv/task-tracker-backend:latest
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
    environment:
      - TASK_TRACKER_BACKEND_API_JWT_KEY
      - TASK_TRACKER_BACKEND_API_ROOT_PATH
      - TASK_TRACKER_BACKEND_API_SMTP_HOST
      - TASK_TRACKER_BACKEND_API_SMTP_PORT
      - TASK_TRACKER_BACKEND_API_SMTP_USERNAME
      - TASK_TRACKER_BACKEND_API_SMTP_PASSWORD
      - TASK_TRACKER_BACKEND_API_MONGODB_URL=mongodb://${TASK_TRACKER_BACKEND_MONGODB_USERNAME}:${TASK_TRACKER_BACKEND_MONGODB_PASSWORD}@mongodb
    ports:
      - ${TASK_TRACKER_BACKEND_API_PORT}:8000
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1G

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${TASK_TRACKER_BACKEND_MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${TASK_TRACKER_BACKEND_MONGODB_PASSWORD}
    restart: unless-stopped
    logging:
      driver: none
